### ISSUE TITLE
Mayaspace is not secure

### ISSUE THREAD

**Issue by peridoqia** [NodeMixaholic/mayaspace#1]
Hello Samuel.

When I setup Mayaspace on my local computer and logged in, I was met with a website titled "The Chinese Truthspeaker"

There is no way to override the post, the "post" button wasn't visible. So I am wondering if you can somehow fix this issue. The vandal also attacked the Mayaspace flagship instance located at https://mayaspace.nodemixaholic.com

It seems that whoever this person is, has vandalized one of the main decentralized databases and so the only thing available is "The Chinese Truthspeaker"

**Comment by peridoqia** [comment]
Ok so, from a quick look at the code, this looks like a client-side social media app with no real security... This seems like an awful idea.

The issue is that we are using a decentralized database that allows anyone to override any message. Anyone can just run `postsDB.put("whatever you want here")` in their browser console and then magically send posts that are shown to every user.

This issue is serious, people can easily bypass the XSS filter you have added and this is exactly what happened here, someone managed to bypass all of the security you added in place.

The solution to these issues is to stop thinking of Mayaspace as a client-side social media app. If we have a real server application then we can enforce anti-XSS measures on the server's side which clients cannot easily bypass.

Unfortunately, we cannot use Gun.js, since Gun.js does not have an anti-XSS filter enabled. (Or maybe it does, but it does not defend against HTML embedding) nor does it have any authentication mechanisms. It would be trivial to bypass the installed server-side XSS filter if the decentralized database Mayaspace is using has no authentication mechanism.

Also, just a quick suggestion, it would be easier for Mayaspace to grow if it adopted some popular federation standards such as ActivityPub or Diaspora instead of gun.js (which, as we have seen before, has no real security)

Oh and also, this is not actually decentralized, we are depending on https://gun-manhattan.herokuapp.com/ which means that if that URL goes down then users won't be able to see our posts.

Please follow some of these suggestions. Mayaspace is not secure whatsoever as it is now.

**Comment by NodeMixaholic** [comment]
i am currently fixing the xss vurn as we speak.

sorry about your bad experiences.

**Comment by NodeMixaholic** [comment]
Good news: Problem mitigated.

Bad news: New problem arises, I can't see other people's post and can only see one at a time.

**Comment by NodeMixaholic** [comment]
also, it IS decentralized, just as torrenting is. https://gun-manhattan.herokuapp.com/ is just a peer discovery server, and so is nodemixaholic.com

**Comment by NodeMixaholic** [comment]
proof of decentralization:

![image](https://github.com/NodeMixaholic/mayaspace/assets/9904667/05785335-73fa-44c5-b6e0-1c75888cb4af)

**Comment by NodeMixaholic** [comment]
btw the ipfs version is hosted here:

https://cloudflare-ipfs.com/ipfs/QmXTNiV8SkT9YrXWTCJco1mg7cSYr9ufzVYNmCnLbQR3R4/

and the normal version is hosted at:

https://mayaspace.nodemixaholic.com/

**Comment by peridoqia** [comment]
Re: Mayaspace is/isn't decentralized. (I know I replied to you outside of GitHub but I want to put this on the record)

The point of decentralization is to ensure that there is no weak link in the chain, gun-manhattan.herokuapp.com is a weak link in the chain since if it goes down then Mayaspace has nowhere else to contact. It follows a peer discovery system like Tor and Torrent (as you have said in your replies)

But peer discovery is not the same as decentralization, decentralization means being free from any centralized sources and that unfortunately includes any peer discovery domains. I am not sure what I would call Mayaspace, maybe "federatable" but definitely not decentralized.

Also, an interesting idea: Write a Mayaspace client that also simultaneously acts as a server. Right now, the client just tries to reach for any existing Gun.js servers on the user's host but I (and many others) block websites from retrieving data on our local machines as a good security measure.
